data_path: hiuman/vietnamese_classification
resume_from_checkpoint: ./models/last.ckpt
distributed_strategy: single
optimizer: adamw
num_classes: 18
batch_size: 8
epochs: 1
deterministic: True
log_every_n_steps: 100